name: CI

on: [push, pull_request]

jobs:
  linux-ci:
    name: Linux
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        config:
          - cc: gcc-10
            cxx: g++-10
            os: ubuntu-22.04

          - cc: gcc-11
            cxx: g++-11
            os: ubuntu-22.04

          - cc: gcc-12
            cxx: g++-12
            os: ubuntu-24.04

          - cc: gcc-13
            cxx: g++-13
            os: ubuntu-24.04

          - cc: gcc-14
            cxx: g++-14
            os: ubuntu-24.04

          - cc: clang-13
            cxx: clang++-13
            os: ubuntu-22.04

          - cc: clang-14
            cxx: clang++-14
            os: ubuntu-22.04

          - cc: clang-15
            cxx: clang++-15
            os: ubuntu-22.04

          - cc: clang-16
            cxx: clang++-16
            os: ubuntu-24.04

          - cc: clang-17
            cxx: clang++-17
            os: ubuntu-24.04

          - cc: clang-18
            cxx: clang++-18
            os: ubuntu-24.04

    runs-on: ${{matrix.config.os}}
    env:
      CC: ${{matrix.config.cc}}
      CXX: ${{matrix.config.cxx}}
      INSTALL_PREFIX: /usr/local
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd ${{runner.workspace}}
          # Build against earliest supported SoapySDR
          git clone https://github.com/pothosware/SoapySDR -b soapy-sdr-0.8.1
          cd SoapySDR
          cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DENABLE_PYTHON=OFF -DENABLE_PYTHON3=OFF -B build
          cmake --build build
          sudo cmake --install build
          sudo ldconfig
      - name: Build SoapyMultiSDR
        run: |
          cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -B build
          cmake --build build
          sudo cmake --install build
      - name: Test module registration
        run: |
          SoapySDRUtil --check=multi

  osx-ci:
    name: OS X
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        config:
          - cc: gcc-12
            cxx: g++-12
            os: macos-15

          - cc: gcc-13
            cxx: g++-13
            os: macos-15

          - cc: gcc-14
            cxx: g++-14
            os: macos-15

          - cc: gcc-15
            cxx: g++-15
            os: macos-15

          - cc: clang
            cxx: clang++
            os: macos-15
    runs-on: ${{matrix.config.os}}
    env:
      CC: ${{matrix.config.cc}}
      CXX: ${{matrix.config.cxx}}
      INSTALL_PREFIX: /usr/local
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd ${{runner.workspace}}
          # Build SoapySDR with updated cmake_minimum_required and fixed rpath
          git clone https://github.com/pothosware/SoapySDR
          cd SoapySDR
          git checkout c4340a2be0f381f5c68a8898f1b52e19c5428c8c
          cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -B build
          cmake --build build
          sudo cmake --install build
      - name: Build SoapyMultiSDR
        run: |
          cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -B build
          cmake --build build
          sudo cmake --install build
      - name: Test module registration
        run: |
          SoapySDRUtil --check=multi

  windows-ci:
    name: Windows
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        config:
          #
          # MSVC
          #
          - cmake_config: -G "Visual Studio 17 2022" -A "Win32"
            arch: win32
            os: windows-2025
            msvc: true

          - cmake_config: -G "Visual Studio 17 2022" -A "x64"
            arch: x64
            os: windows-2025
            msvc: true

          #
          # MinGW
          #
          - cmake_config: -G "MinGW Makefiles"
            os: windows-2025
            msvc: false
    runs-on: ${{matrix.config.os}}
    env:
      INSTALL_PREFIX: 'C:\Program Files\SoapySDR'
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        if:
          ${{matrix.config.msvc == true}}
        with:
          arch: ${{matrix.config.arch}}
      - name: Install SoapySDR
        run: |
          cd ${{runner.workspace}}
          # Build SoapySDR that supports OS X GCC modules
          git clone https://github.com/pothosware/SoapySDR
          cd SoapySDR
          git checkout f8d57652d12f9d212f373a81e493eba1a0b058c5
          cmake ${{matrix.config.cmake_config}} -DENABLE_PYTHON=OFF -DCMAKE_INSTALL_PREFIX="$Env:INSTALL_PREFIX" -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -B build
          cmake --build build --config ${{matrix.build_type}}
          cmake --install build --config ${{matrix.build_type}}
      - name: Build SoapyMultiSDR
        run: |
          $Env:INCLUDE += ";$Env:INSTALL_PREFIX\include"
          $Env:LIB += ";$Env:INSTALL_PREFIX\lib"
          cmake ${{matrix.config.cmake_config}} -DCMAKE_INSTALL_PREFIX="$Env:INSTALL_PREFIX" -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -B build
          cmake --build build --config ${{matrix.build_type}}
          cmake --install build --config ${{matrix.build_type}}
      - name: Test module registration
        run: |
          $Env:PATH += ";$Env:INSTALL_PREFIX\bin"
          SoapySDRUtil --check=multi

  freebsd-ci:
    name: FreeBSD
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        release: ["13.5", "14.3", "15.0"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/freebsd-vm@v1
        name: Test in FreeBSD
        with:
          release: ${{matrix.release}}
          copyback: false
          prepare: |
            pkg install -y sudo cmake SoapySDR net/avahi
          run: |
            # We can't separate these steps, so add prints for clarity.

            echo
            echo "----------------------------------"
            echo "Building..."
            echo "----------------------------------"
            cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -B build
            cmake --build build

            echo
            echo "----------------------------------"
            echo "Installing..."
            echo "----------------------------------"
            sudo cmake --install build

            echo
            echo "----------------------------------"
            echo "Testing module registration..."
            echo "----------------------------------"
            SoapySDRUtil --check=multi
